
%%%% Autor: Philipp Amrein, University Freiburg, Medical Center, Radiology,
%%%% Medical Physics
%%%% February 2022


clc; clear all; close all;



if ispc
cd('..\');
else
cd('../');
end


close all;


%% Run the algorithm

  %  'field_shape_function','(x.*x+0.7.*y.*y).^(1/2)',... % definition of the target field

%tik_factor=4000;
%tik_factor=[1000 1500 2000 2500 3000];
tik_factor=1000;
%tik_factor=[1:10:100 150:50:500 600:100:1000 2000:1000:10000 20000:10000:50000];
num_iteration=5000;
fmincon_parameter=[num_iteration 10^10 1.000000e-14 10^(-18) 10^(-18)];
num_levels=30;
optim_method='tikkonov';
target_region_res=10;
skip_postprocessing=true;
iteration_num_mesh_refinement=1;
min_loop_signifcance=0.001;
target_field_definition_file='intraoral_dental_target_field.mat';
coil_mesh_file='dental_extraoral_ccs2_shifted_2cm_in_y.stl'; 
surface_is_cylinder_flag=true;
normal_shift_length=0.001;
pot_offset_factor=0.25;
interconnection_cut_width=0.002;
skip_inductance_calculation=false;



[coil_x,~]=CoilGen(...
'target_field_definition_file',target_field_definition_file,...
'target_field_definition_field_name','lin_x',...
'coil_mesh_file',coil_mesh_file, ... 
'min_loop_signifcance',min_loop_signifcance,...
'iteration_num_mesh_refinement',iteration_num_mesh_refinement,...
'target_region_resolution',target_region_res,...
'use_only_target_mesh_verts',false, ...
'levels',num_levels, ... % the number of potential steps that determines the later number of windings (Stream function discretization)
'pot_offset_factor',pot_offset_factor, ... % a potential offset value for the minimal and maximal contour potential ; must be between 0 and 1
'surface_is_cylinder_flag',surface_is_cylinder_flag, ...
'interconnection_cut_width',interconnection_cut_width, ... % the width for the interconnections are interconnected; in meter
'normal_shift_length',normal_shift_length, ... % the length for which overlapping return paths will be shifted along the surface normals; in meter
'set_roi_into_mesh_center',true, ...
'force_cut_selection',{'high'},...
'level_set_method','primary',... %Specify one of the three ways the level sets are calculated: "primary","combined", or "independent"
'interconnection_method','regular',...
'skip_postprocessing',skip_postprocessing,...
'skip_sweep',true,...
'skip_inductance_calculation',skip_inductance_calculation,...
'sf_opt_method',optim_method,...
'fmincon_parameter',fmincon_parameter,...
'tikonov_reg_factor',tik_factor); %Tikonov regularization factor for the SF optimization




[coil_y,~]=CoilGen(...
'target_field_definition_file',target_field_definition_file,...
'target_field_definition_field_name','lin_y',...
'coil_mesh_file',coil_mesh_file, ... 
'min_loop_signifcance',min_loop_signifcance,...
'iteration_num_mesh_refinement',iteration_num_mesh_refinement,...
'target_region_resolution',target_region_res,...
'use_only_target_mesh_verts',false, ...
'levels',num_levels, ... % the number of potential steps that determines the later number of windings (Stream function discretization)
'pot_offset_factor',pot_offset_factor, ... % a potential offset value for the minimal and maximal contour potential ; must be between 0 and 1
'surface_is_cylinder_flag',surface_is_cylinder_flag, ...
'interconnection_cut_width',interconnection_cut_width, ... % the width for the interconnections are interconnected; in meter
'normal_shift_length',normal_shift_length, ... % the length for which overlapping return paths will be shifted along the surface normals; in meter
'set_roi_into_mesh_center',true, ...
'force_cut_selection',{'high'},...
'level_set_method','primary',... %Specify one of the three ways the level sets are calculated: "primary","combined", or "independent"
'interconnection_method','regular',...
'skip_postprocessing',skip_postprocessing,...
'skip_sweep',true,...
'skip_inductance_calculation',skip_inductance_calculation,...
'sf_opt_method',optim_method,...
'fmincon_parameter',fmincon_parameter,...
'tikonov_reg_factor',tik_factor); %Tikonov regularization factor for the SF optimization




[coil_z,~]=CoilGen(...
'target_field_definition_file',target_field_definition_file,...
'target_field_definition_field_name','lin_z',...
'coil_mesh_file',coil_mesh_file, ... 
'min_loop_signifcance',min_loop_signifcance,...
'iteration_num_mesh_refinement',iteration_num_mesh_refinement,...
'target_region_resolution',target_region_res,...
'use_only_target_mesh_verts',false, ...
'levels',num_levels, ... % the number of potential steps that determines the later number of windings (Stream function discretization)
'pot_offset_factor',pot_offset_factor, ... % a potential offset value for the minimal and maximal contour potential ; must be between 0 and 1
'surface_is_cylinder_flag',surface_is_cylinder_flag, ...
'interconnection_cut_width',interconnection_cut_width, ... % the width for the interconnections are interconnected; in meter
'normal_shift_length',normal_shift_length, ... % the length for which overlapping return paths will be shifted along the surface normals; in meter
'set_roi_into_mesh_center',true, ...
'force_cut_selection',{'high'},...
'level_set_method','primary',... %Specify one of the three ways the level sets are calculated: "primary","combined", or "independent"
'interconnection_method','regular',...
'skip_postprocessing',skip_postprocessing,...
'skip_sweep',true,...
'skip_inductance_calculation',skip_inductance_calculation,...
'sf_opt_method',optim_method,...
'fmincon_parameter',fmincon_parameter,...
'tikonov_reg_factor',tik_factor); %Tikonov regularization factor for the SF optimization



[coil_r,~]=CoilGen(...
'target_field_definition_file',target_field_definition_file,...
'target_field_definition_field_name','r',...
'coil_mesh_file',coil_mesh_file, ... 
'min_loop_signifcance',min_loop_signifcance,...
'iteration_num_mesh_refinement',iteration_num_mesh_refinement,...
'target_region_resolution',target_region_res,...
'use_only_target_mesh_verts',false, ...
'levels',num_levels, ... % the number of potential steps that determines the later number of windings (Stream function discretization)
'pot_offset_factor',pot_offset_factor, ... % a potential offset value for the minimal and maximal contour potential ; must be between 0 and 1
'surface_is_cylinder_flag',surface_is_cylinder_flag, ...
'interconnection_cut_width',interconnection_cut_width, ... % the width for the interconnections are interconnected; in meter
'normal_shift_length',normal_shift_length, ... % the length for which overlapping return paths will be shifted along the surface normals; in meter
'set_roi_into_mesh_center',true, ...
'force_cut_selection',{'high'},...
'level_set_method','primary',... %Specify one of the three ways the level sets are calculated: "primary","combined", or "independent"
'interconnection_method','regular',...
'skip_postprocessing',skip_postprocessing,...
'skip_sweep',true,...
'skip_inductance_calculation',skip_inductance_calculation,...
'sf_opt_method',optim_method,...
'fmincon_parameter',fmincon_parameter,...
'tikonov_reg_factor',tik_factor); %Tikonov regularization factor for the SF optimization


[coil_phi,temp]=CoilGen(...
'target_field_definition_file',target_field_definition_file,...
'target_field_definition_field_name','phi',...
'coil_mesh_file',coil_mesh_file, ... 
'min_loop_signifcance',min_loop_signifcance,...
'iteration_num_mesh_refinement',iteration_num_mesh_refinement,...
'target_region_resolution',target_region_res,...
'use_only_target_mesh_verts',false, ...
'levels',num_levels, ... % the number of potential steps that determines the later number of windings (Stream function discretization)
'pot_offset_factor',pot_offset_factor, ... % a potential offset value for the minimal and maximal contour potential ; must be between 0 and 1
'surface_is_cylinder_flag',surface_is_cylinder_flag, ...
'interconnection_cut_width',interconnection_cut_width, ... % the width for the interconnections are interconnected; in meter
'normal_shift_length',normal_shift_length, ... % the length for which overlapping return paths will be shifted along the surface normals; in meter
'set_roi_into_mesh_center',true, ...
'force_cut_selection',{'high'},...
'level_set_method','primary',... %Specify one of the three ways the level sets are calculated: "primary","combined", or "independent"
'interconnection_method','regular',...
'skip_postprocessing',skip_postprocessing,...
'skip_sweep',true,...
'skip_inductance_calculation',skip_inductance_calculation,...
'sf_opt_method',optim_method,...
'fmincon_parameter',fmincon_parameter,...
'tikonov_reg_factor',tik_factor); %Tikonov regularization factor for the SF optimization



%% Plot results
close all;


coil_to_plot.out=coil_r;
single_ind_to_plot = 1;

if ispc
addpath(strcat(pwd,'\','plotting'));
else
addpath(strcat(pwd,'/','plotting'));
end
coil_name='Coil';
%Chose a even leveled solution for plotting
%plot_error_different_solutions(coil_to_plot,single_ind_to_plot,coil_name);
% plot_2D_contours_with_sf(coil_to_plot,single_ind_to_plot,coil_name);
% plot_3D_sf(coil_to_plot,single_ind_to_plot,coil_name);
plot_groups_and_interconnections(coil_to_plot,single_ind_to_plot,coil_name);
plot_coil_parameters(coil_to_plot,coil_name);
plot_coil_track_with_resulting_bfield(coil_to_plot,single_ind_to_plot,coil_name);
plot_various_error_metrics(coil_to_plot,single_ind_to_plot,coil_name);
std_gradient=plot_resulting_gradient(coil_to_plot,single_ind_to_plot,coil_name);
rmpath('plotting');

